### ISSUE TITLE
Fix for Sentinel-2 Field Parcel Extraction

### ISSUE THREAD

**Issue by leonard-psu** [EOA-team/eodal_notebooks#17]
In notebook "Sentinel-2 Field Parcel Extraction"

from eodal.downloader.sentinel2.utils import unzip_datasets

needs to be changed to 

from eodal.downloader.utils import unzip_datasets

**Comment by lukasValentin** [comment]
Hi @leonard-psu thanks for spotting this - could you open an PR and propose the changes directly in the code?
